// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDs9pbE1EhDLR8VV3dX50PNlC-6pkSbSAs',
    appId: '1:198089608631:web:7f2a0045c5ac68447dac32',
    messagingSenderId: '198089608631',
    projectId: 'socialmediaapp-1ed71',
    authDomain: 'socialmediaapp-1ed71.firebaseapp.com',
    storageBucket: 'socialmediaapp-1ed71.appspot.com',
    measurementId: 'G-FG8DBBNK4Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzqv_brtWgvr2Xs44C0n5ZbusntMT9_rg',
    appId: '1:198089608631:android:c5f83db9a06359e47dac32',
    messagingSenderId: '198089608631',
    projectId: 'socialmediaapp-1ed71',
    storageBucket: 'socialmediaapp-1ed71.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-WasirmEiF7gVxr719GcF83yNqvLhHag',
    appId: '1:198089608631:ios:2b86244d00c2814e7dac32',
    messagingSenderId: '198089608631',
    projectId: 'socialmediaapp-1ed71',
    storageBucket: 'socialmediaapp-1ed71.appspot.com',
    iosBundleId: 'com.example.emeka',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-WasirmEiF7gVxr719GcF83yNqvLhHag',
    appId: '1:198089608631:ios:27494cb13242bd827dac32',
    messagingSenderId: '198089608631',
    projectId: 'socialmediaapp-1ed71',
    storageBucket: 'socialmediaapp-1ed71.appspot.com',
    iosBundleId: 'com.example.social',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDs9pbE1EhDLR8VV3dX50PNlC-6pkSbSAs',
    appId: '1:198089608631:web:6f0b1bf239d2ce717dac32',
    messagingSenderId: '198089608631',
    projectId: 'socialmediaapp-1ed71',
    authDomain: 'socialmediaapp-1ed71.firebaseapp.com',
    storageBucket: 'socialmediaapp-1ed71.appspot.com',
    measurementId: 'G-K0QM6WRXZ4',
  );
}
